# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.omrder_api import OmrderApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOmrderApi(unittest.TestCase):
    """OmrderApi unit test stubs"""

    def setUp(self):
        self.api = OmrderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_omrader_fylker_get(self):
        """Test case for omrader_fylker_get

        """
        pass

    def test_omrader_get(self):
        """Test case for omrader_get

        """
        pass

    def test_omrader_kommuner_get(self):
        """Test case for omrader_kommuner_get

        """
        pass

    def test_omrader_kontraktomrader_get(self):
        """Test case for omrader_kontraktomrader_get

        """
        pass

    def test_omrader_riksvegruter_get(self):
        """Test case for omrader_riksvegruter_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
