# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_ofvegobjekt_lokasjon_stedfesting import OneOfvegobjektLokasjonStedfesting  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfvegobjektLokasjonStedfesting(unittest.TestCase):
    """OneOfvegobjektLokasjonStedfesting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfvegobjektLokasjonStedfesting(self):
        """Test OneOfvegobjektLokasjonStedfesting"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_ofvegobjekt_lokasjon_stedfesting.OneOfvegobjektLokasjonStedfesting()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
