# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.transaksjoner_api import TransaksjonerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTransaksjonerApi(unittest.TestCase):
    """TransaksjonerApi unit test stubs"""

    def setUp(self):
        self.api = TransaksjonerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_status_get(self):
        """Test case for status_get

        """
        pass

    def test_transaksjoner_get(self):
        """Test case for transaksjoner_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
