# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.posisjon_api import PosisjonApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPosisjonApi(unittest.TestCase):
    """PosisjonApi unit test stubs"""

    def setUp(self):
        self.api = PosisjonApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_posisjon_get(self):
        """Test case for posisjon_get

        """
        pass

    def test_veg_batch_get(self):
        """Test case for veg_batch_get

        """
        pass

    def test_veg_get(self):
        """Test case for veg_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
