# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.vegobjekt_egenskap import VegobjektEgenskap  # noqa: E501
from swagger_client.rest import ApiException


class TestVegobjektEgenskap(unittest.TestCase):
    """VegobjektEgenskap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVegobjektEgenskap(self):
        """Test VegobjektEgenskap"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.vegobjekt_egenskap.VegobjektEgenskap()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
