# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.vegnett_api import VegnettApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVegnettApi(unittest.TestCase):
    """VegnettApi unit test stubs"""

    def setUp(self):
        self.api = VegnettApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_beta_vegnett_rute_get(self):
        """Test case for beta_vegnett_rute_get

        """
        pass

    def test_beta_vegnett_rute_post(self):
        """Test case for beta_vegnett_rute_post

        """
        pass

    def test_posisjon_get(self):
        """Test case for posisjon_get

        """
        pass

    def test_veg_batch_get(self):
        """Test case for veg_batch_get

        """
        pass

    def test_veg_get(self):
        """Test case for veg_get

        """
        pass

    def test_vegnett_get(self):
        """Test case for vegnett_get

        """
        pass

    def test_vegnett_noder_get(self):
        """Test case for vegnett_noder_get

        """
        pass

    def test_vegnett_noder_nodeid_get(self):
        """Test case for vegnett_noder_nodeid_get

        """
        pass

    def test_vegnett_veglenkesekvenser_get(self):
        """Test case for vegnett_veglenkesekvenser_get

        """
        pass

    def test_vegnett_veglenkesekvenser_segmentert_get(self):
        """Test case for vegnett_veglenkesekvenser_segmentert_get

        """
        pass

    def test_vegnett_veglenkesekvenser_segmentert_veglenkesekvensid_get(self):
        """Test case for vegnett_veglenkesekvenser_segmentert_veglenkesekvensid_get

        """
        pass

    def test_vegnett_veglenkesekvenser_veglenkesekvensid_get(self):
        """Test case for vegnett_veglenkesekvenser_veglenkesekvensid_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
