# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response2008_kjorende_oppgave import InlineResponse2008KjorendeOppgave  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse2008KjorendeOppgave(unittest.TestCase):
    """InlineResponse2008KjorendeOppgave unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2008KjorendeOppgave(self):
        """Test InlineResponse2008KjorendeOppgave"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response2008_kjorende_oppgave.InlineResponse2008KjorendeOppgave()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
