# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.datakatalog_api import DatakatalogApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDatakatalogApi(unittest.TestCase):
    """DatakatalogApi unit test stubs"""

    def setUp(self):
        self.api = DatakatalogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_status_get(self):
        """Test case for status_get

        """
        pass

    def test_vegobjekttyper_datatyper_get(self):
        """Test case for vegobjekttyper_datatyper_get

        """
        pass

    def test_vegobjekttyper_egenskapstypekategorier_get(self):
        """Test case for vegobjekttyper_egenskapstypekategorier_get

        """
        pass

    def test_vegobjekttyper_enheter_get(self):
        """Test case for vegobjekttyper_enheter_get

        """
        pass

    def test_vegobjekttyper_get(self):
        """Test case for vegobjekttyper_get

        """
        pass

    def test_vegobjekttyper_kategorier_get(self):
        """Test case for vegobjekttyper_kategorier_get

        """
        pass

    def test_vegobjekttyper_vegobjekttypeid_get(self):
        """Test case for vegobjekttyper_vegobjekttypeid_get

        """
        pass

    def test_vegobjekttyper_version_get(self):
        """Test case for vegobjekttyper_version_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
