# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.vegobjekter_api import VegobjekterApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVegobjekterApi(unittest.TestCase):
    """VegobjekterApi unit test stubs"""

    def setUp(self):
        self.api = VegobjekterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_vegobjekt_get(self):
        """Test case for vegobjekt_get

        """
        pass

    def test_vegobjekter_get(self):
        """Test case for vegobjekter_get

        """
        pass

    def test_vegobjekter_statistikk_get(self):
        """Test case for vegobjekter_statistikk_get

        """
        pass

    def test_vegobjekter_vegobjekttypeid_get(self):
        """Test case for vegobjekter_vegobjekttypeid_get

        """
        pass

    def test_vegobjekter_vegobjekttypeid_statistikk_get(self):
        """Test case for vegobjekter_vegobjekttypeid_statistikk_get

        """
        pass

    def test_vegobjekter_vegobjekttypeid_vegobjektid_get(self):
        """Test case for vegobjekter_vegobjekttypeid_vegobjektid_get

        """
        pass

    def test_vegobjekter_vegobjekttypeid_vegobjektid_versjon_egenskaper_egenskapid_binaerobjektid_binaer_get(self):
        """Test case for vegobjekter_vegobjekttypeid_vegobjektid_versjon_egenskaper_egenskapid_binaerobjektid_binaer_get

        """
        pass

    def test_vegobjekter_vegobjekttypeid_vegobjektid_versjon_get(self):
        """Test case for vegobjekter_vegobjekttypeid_vegobjektid_versjon_get

        """
        pass

    def test_vegobjekter_vegobjekttypeid_vegobjektid_versjoner_get(self):
        """Test case for vegobjekter_vegobjekttypeid_vegobjektid_versjoner_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
