# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.meter_referanse import MeterReferanse  # noqa: F401,E501

class AllOfvegsystemreferanseSidealegg(MeterReferanse):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'version': 'int',
        'sideanlegg': 'int',
        'sideanleggsdel': 'int',
        'trafikantgruppe': 'str',
        'retning': 'Retning'
    }
    if hasattr(MeterReferanse, "swagger_types"):
        swagger_types.update(MeterReferanse.swagger_types)

    attribute_map = {
        'id': 'id',
        'version': 'version',
        'sideanlegg': 'sideanlegg',
        'sideanleggsdel': 'sideanleggsdel',
        'trafikantgruppe': 'trafikantgruppe',
        'retning': 'retning'
    }
    if hasattr(MeterReferanse, "attribute_map"):
        attribute_map.update(MeterReferanse.attribute_map)

    def __init__(self, id=None, version=None, sideanlegg=None, sideanleggsdel=None, trafikantgruppe=None, retning=None, *args, **kwargs):  # noqa: E501
        """AllOfvegsystemreferanseSidealegg - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._version = None
        self._sideanlegg = None
        self._sideanleggsdel = None
        self._trafikantgruppe = None
        self._retning = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if version is not None:
            self.version = version
        if sideanlegg is not None:
            self.sideanlegg = sideanlegg
        if sideanleggsdel is not None:
            self.sideanleggsdel = sideanleggsdel
        if trafikantgruppe is not None:
            self.trafikantgruppe = trafikantgruppe
        if retning is not None:
            self.retning = retning
        MeterReferanse.__init__(self, *args, **kwargs)

    @property
    def id(self):
        """Gets the id of this AllOfvegsystemreferanseSidealegg.  # noqa: E501

        Fraværende for objekters vegsystemreferanse  # noqa: E501

        :return: The id of this AllOfvegsystemreferanseSidealegg.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AllOfvegsystemreferanseSidealegg.

        Fraværende for objekters vegsystemreferanse  # noqa: E501

        :param id: The id of this AllOfvegsystemreferanseSidealegg.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def version(self):
        """Gets the version of this AllOfvegsystemreferanseSidealegg.  # noqa: E501

        Fraværende for objekters vegsystemreferanse  # noqa: E501

        :return: The version of this AllOfvegsystemreferanseSidealegg.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this AllOfvegsystemreferanseSidealegg.

        Fraværende for objekters vegsystemreferanse  # noqa: E501

        :param version: The version of this AllOfvegsystemreferanseSidealegg.  # noqa: E501
        :type: int
        """

        self._version = version

    @property
    def sideanlegg(self):
        """Gets the sideanlegg of this AllOfvegsystemreferanseSidealegg.  # noqa: E501


        :return: The sideanlegg of this AllOfvegsystemreferanseSidealegg.  # noqa: E501
        :rtype: int
        """
        return self._sideanlegg

    @sideanlegg.setter
    def sideanlegg(self, sideanlegg):
        """Sets the sideanlegg of this AllOfvegsystemreferanseSidealegg.


        :param sideanlegg: The sideanlegg of this AllOfvegsystemreferanseSidealegg.  # noqa: E501
        :type: int
        """

        self._sideanlegg = sideanlegg

    @property
    def sideanleggsdel(self):
        """Gets the sideanleggsdel of this AllOfvegsystemreferanseSidealegg.  # noqa: E501


        :return: The sideanleggsdel of this AllOfvegsystemreferanseSidealegg.  # noqa: E501
        :rtype: int
        """
        return self._sideanleggsdel

    @sideanleggsdel.setter
    def sideanleggsdel(self, sideanleggsdel):
        """Sets the sideanleggsdel of this AllOfvegsystemreferanseSidealegg.


        :param sideanleggsdel: The sideanleggsdel of this AllOfvegsystemreferanseSidealegg.  # noqa: E501
        :type: int
        """

        self._sideanleggsdel = sideanleggsdel

    @property
    def trafikantgruppe(self):
        """Gets the trafikantgruppe of this AllOfvegsystemreferanseSidealegg.  # noqa: E501


        :return: The trafikantgruppe of this AllOfvegsystemreferanseSidealegg.  # noqa: E501
        :rtype: str
        """
        return self._trafikantgruppe

    @trafikantgruppe.setter
    def trafikantgruppe(self, trafikantgruppe):
        """Sets the trafikantgruppe of this AllOfvegsystemreferanseSidealegg.


        :param trafikantgruppe: The trafikantgruppe of this AllOfvegsystemreferanseSidealegg.  # noqa: E501
        :type: str
        """
        allowed_values = ["K", "G"]  # noqa: E501
        if trafikantgruppe not in allowed_values:
            raise ValueError(
                "Invalid value for `trafikantgruppe` ({0}), must be one of {1}"  # noqa: E501
                .format(trafikantgruppe, allowed_values)
            )

        self._trafikantgruppe = trafikantgruppe

    @property
    def retning(self):
        """Gets the retning of this AllOfvegsystemreferanseSidealegg.  # noqa: E501


        :return: The retning of this AllOfvegsystemreferanseSidealegg.  # noqa: E501
        :rtype: Retning
        """
        return self._retning

    @retning.setter
    def retning(self, retning):
        """Sets the retning of this AllOfvegsystemreferanseSidealegg.


        :param retning: The retning of this AllOfvegsystemreferanseSidealegg.  # noqa: E501
        :type: Retning
        """

        self._retning = retning

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AllOfvegsystemreferanseSidealegg, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AllOfvegsystemreferanseSidealegg):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
