# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2003(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'navn': 'str',
        'kortnavn': 'str',
        'sorteringsnummer': 'int',
        'beskrivelse': 'str',
        'startdato': 'date'
    }

    attribute_map = {
        'id': 'id',
        'navn': 'navn',
        'kortnavn': 'kortnavn',
        'sorteringsnummer': 'sorteringsnummer',
        'beskrivelse': 'beskrivelse',
        'startdato': 'startdato'
    }

    def __init__(self, id=None, navn=None, kortnavn=None, sorteringsnummer=None, beskrivelse=None, startdato=None):  # noqa: E501
        """InlineResponse2003 - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._navn = None
        self._kortnavn = None
        self._sorteringsnummer = None
        self._beskrivelse = None
        self._startdato = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if navn is not None:
            self.navn = navn
        if kortnavn is not None:
            self.kortnavn = kortnavn
        if sorteringsnummer is not None:
            self.sorteringsnummer = sorteringsnummer
        if beskrivelse is not None:
            self.beskrivelse = beskrivelse
        if startdato is not None:
            self.startdato = startdato

    @property
    def id(self):
        """Gets the id of this InlineResponse2003.  # noqa: E501


        :return: The id of this InlineResponse2003.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2003.


        :param id: The id of this InlineResponse2003.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def navn(self):
        """Gets the navn of this InlineResponse2003.  # noqa: E501


        :return: The navn of this InlineResponse2003.  # noqa: E501
        :rtype: str
        """
        return self._navn

    @navn.setter
    def navn(self, navn):
        """Sets the navn of this InlineResponse2003.


        :param navn: The navn of this InlineResponse2003.  # noqa: E501
        :type: str
        """

        self._navn = navn

    @property
    def kortnavn(self):
        """Gets the kortnavn of this InlineResponse2003.  # noqa: E501


        :return: The kortnavn of this InlineResponse2003.  # noqa: E501
        :rtype: str
        """
        return self._kortnavn

    @kortnavn.setter
    def kortnavn(self, kortnavn):
        """Sets the kortnavn of this InlineResponse2003.


        :param kortnavn: The kortnavn of this InlineResponse2003.  # noqa: E501
        :type: str
        """

        self._kortnavn = kortnavn

    @property
    def sorteringsnummer(self):
        """Gets the sorteringsnummer of this InlineResponse2003.  # noqa: E501


        :return: The sorteringsnummer of this InlineResponse2003.  # noqa: E501
        :rtype: int
        """
        return self._sorteringsnummer

    @sorteringsnummer.setter
    def sorteringsnummer(self, sorteringsnummer):
        """Sets the sorteringsnummer of this InlineResponse2003.


        :param sorteringsnummer: The sorteringsnummer of this InlineResponse2003.  # noqa: E501
        :type: int
        """

        self._sorteringsnummer = sorteringsnummer

    @property
    def beskrivelse(self):
        """Gets the beskrivelse of this InlineResponse2003.  # noqa: E501


        :return: The beskrivelse of this InlineResponse2003.  # noqa: E501
        :rtype: str
        """
        return self._beskrivelse

    @beskrivelse.setter
    def beskrivelse(self, beskrivelse):
        """Sets the beskrivelse of this InlineResponse2003.


        :param beskrivelse: The beskrivelse of this InlineResponse2003.  # noqa: E501
        :type: str
        """

        self._beskrivelse = beskrivelse

    @property
    def startdato(self):
        """Gets the startdato of this InlineResponse2003.  # noqa: E501


        :return: The startdato of this InlineResponse2003.  # noqa: E501
        :rtype: date
        """
        return self._startdato

    @startdato.setter
    def startdato(self, startdato):
        """Sets the startdato of this InlineResponse2003.


        :param startdato: The startdato of this InlineResponse2003.  # noqa: E501
        :type: date
        """

        self._startdato = startdato

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2003, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2003):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
