# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2008DatagrunnlagSistProsesserteTransaksjon(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'transaksjonsid': 'int',
        'transaksjonstidspunkt': 'str'
    }

    attribute_map = {
        'transaksjonsid': 'transaksjonsid',
        'transaksjonstidspunkt': 'transaksjonstidspunkt'
    }

    def __init__(self, transaksjonsid=None, transaksjonstidspunkt=None):  # noqa: E501
        """InlineResponse2008DatagrunnlagSistProsesserteTransaksjon - a model defined in Swagger"""  # noqa: E501
        self._transaksjonsid = None
        self._transaksjonstidspunkt = None
        self.discriminator = None
        if transaksjonsid is not None:
            self.transaksjonsid = transaksjonsid
        if transaksjonstidspunkt is not None:
            self.transaksjonstidspunkt = transaksjonstidspunkt

    @property
    def transaksjonsid(self):
        """Gets the transaksjonsid of this InlineResponse2008DatagrunnlagSistProsesserteTransaksjon.  # noqa: E501


        :return: The transaksjonsid of this InlineResponse2008DatagrunnlagSistProsesserteTransaksjon.  # noqa: E501
        :rtype: int
        """
        return self._transaksjonsid

    @transaksjonsid.setter
    def transaksjonsid(self, transaksjonsid):
        """Sets the transaksjonsid of this InlineResponse2008DatagrunnlagSistProsesserteTransaksjon.


        :param transaksjonsid: The transaksjonsid of this InlineResponse2008DatagrunnlagSistProsesserteTransaksjon.  # noqa: E501
        :type: int
        """

        self._transaksjonsid = transaksjonsid

    @property
    def transaksjonstidspunkt(self):
        """Gets the transaksjonstidspunkt of this InlineResponse2008DatagrunnlagSistProsesserteTransaksjon.  # noqa: E501


        :return: The transaksjonstidspunkt of this InlineResponse2008DatagrunnlagSistProsesserteTransaksjon.  # noqa: E501
        :rtype: str
        """
        return self._transaksjonstidspunkt

    @transaksjonstidspunkt.setter
    def transaksjonstidspunkt(self, transaksjonstidspunkt):
        """Sets the transaksjonstidspunkt of this InlineResponse2008DatagrunnlagSistProsesserteTransaksjon.


        :param transaksjonstidspunkt: The transaksjonstidspunkt of this InlineResponse2008DatagrunnlagSistProsesserteTransaksjon.  # noqa: E501
        :type: str
        """

        self._transaksjonstidspunkt = transaksjonstidspunkt

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2008DatagrunnlagSistProsesserteTransaksjon, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2008DatagrunnlagSistProsesserteTransaksjon):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
