# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Port(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'relativ_posisjon': 'float',
        'tilkobling': 'PortTilkobling'
    }

    attribute_map = {
        'id': 'id',
        'relativ_posisjon': 'relativPosisjon',
        'tilkobling': 'tilkobling'
    }

    def __init__(self, id=None, relativ_posisjon=None, tilkobling=None):  # noqa: E501
        """Port - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._relativ_posisjon = None
        self._tilkobling = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if relativ_posisjon is not None:
            self.relativ_posisjon = relativ_posisjon
        if tilkobling is not None:
            self.tilkobling = tilkobling

    @property
    def id(self):
        """Gets the id of this Port.  # noqa: E501


        :return: The id of this Port.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Port.


        :param id: The id of this Port.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def relativ_posisjon(self):
        """Gets the relativ_posisjon of this Port.  # noqa: E501


        :return: The relativ_posisjon of this Port.  # noqa: E501
        :rtype: float
        """
        return self._relativ_posisjon

    @relativ_posisjon.setter
    def relativ_posisjon(self, relativ_posisjon):
        """Sets the relativ_posisjon of this Port.


        :param relativ_posisjon: The relativ_posisjon of this Port.  # noqa: E501
        :type: float
        """

        self._relativ_posisjon = relativ_posisjon

    @property
    def tilkobling(self):
        """Gets the tilkobling of this Port.  # noqa: E501


        :return: The tilkobling of this Port.  # noqa: E501
        :rtype: PortTilkobling
        """
        return self._tilkobling

    @tilkobling.setter
    def tilkobling(self, tilkobling):
        """Sets the tilkobling of this Port.


        :param tilkobling: The tilkobling of this Port.  # noqa: E501
        :type: PortTilkobling
        """

        self._tilkobling = tilkobling

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Port, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Port):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
