# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PortTilkobling(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'portnummer': 'int',
        'nodeid': 'int',
        'href': 'str'
    }

    attribute_map = {
        'portnummer': 'portnummer',
        'nodeid': 'nodeid',
        'href': 'href'
    }

    def __init__(self, portnummer=None, nodeid=None, href=None):  # noqa: E501
        """PortTilkobling - a model defined in Swagger"""  # noqa: E501
        self._portnummer = None
        self._nodeid = None
        self._href = None
        self.discriminator = None
        if portnummer is not None:
            self.portnummer = portnummer
        if nodeid is not None:
            self.nodeid = nodeid
        if href is not None:
            self.href = href

    @property
    def portnummer(self):
        """Gets the portnummer of this PortTilkobling.  # noqa: E501


        :return: The portnummer of this PortTilkobling.  # noqa: E501
        :rtype: int
        """
        return self._portnummer

    @portnummer.setter
    def portnummer(self, portnummer):
        """Sets the portnummer of this PortTilkobling.


        :param portnummer: The portnummer of this PortTilkobling.  # noqa: E501
        :type: int
        """

        self._portnummer = portnummer

    @property
    def nodeid(self):
        """Gets the nodeid of this PortTilkobling.  # noqa: E501


        :return: The nodeid of this PortTilkobling.  # noqa: E501
        :rtype: int
        """
        return self._nodeid

    @nodeid.setter
    def nodeid(self, nodeid):
        """Sets the nodeid of this PortTilkobling.


        :param nodeid: The nodeid of this PortTilkobling.  # noqa: E501
        :type: int
        """

        self._nodeid = nodeid

    @property
    def href(self):
        """Gets the href of this PortTilkobling.  # noqa: E501


        :return: The href of this PortTilkobling.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this PortTilkobling.


        :param href: The href of this PortTilkobling.  # noqa: E501
        :type: str
        """

        self._href = href

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PortTilkobling, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PortTilkobling):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
