# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PosisjonsresultatGeometri(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'wkt': 'str',
        'srid': 'int'
    }

    attribute_map = {
        'wkt': 'wkt',
        'srid': 'srid'
    }

    def __init__(self, wkt=None, srid=5973):  # noqa: E501
        """PosisjonsresultatGeometri - a model defined in Swagger"""  # noqa: E501
        self._wkt = None
        self._srid = None
        self.discriminator = None
        if wkt is not None:
            self.wkt = wkt
        if srid is not None:
            self.srid = srid

    @property
    def wkt(self):
        """Gets the wkt of this PosisjonsresultatGeometri.  # noqa: E501


        :return: The wkt of this PosisjonsresultatGeometri.  # noqa: E501
        :rtype: str
        """
        return self._wkt

    @wkt.setter
    def wkt(self, wkt):
        """Sets the wkt of this PosisjonsresultatGeometri.


        :param wkt: The wkt of this PosisjonsresultatGeometri.  # noqa: E501
        :type: str
        """

        self._wkt = wkt

    @property
    def srid(self):
        """Gets the srid of this PosisjonsresultatGeometri.  # noqa: E501


        :return: The srid of this PosisjonsresultatGeometri.  # noqa: E501
        :rtype: int
        """
        return self._srid

    @srid.setter
    def srid(self, srid):
        """Sets the srid of this PosisjonsresultatGeometri.


        :param srid: The srid of this PosisjonsresultatGeometri.  # noqa: E501
        :type: int
        """

        self._srid = srid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PosisjonsresultatGeometri, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PosisjonsresultatGeometri):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
