# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RelasjonBase(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'listeid': 'int',
        'id': 'int',
        'type': 'RelasjonbaseType'
    }

    attribute_map = {
        'listeid': 'listeid',
        'id': 'id',
        'type': 'type'
    }

    def __init__(self, listeid=None, id=None, type=None):  # noqa: E501
        """RelasjonBase - a model defined in Swagger"""  # noqa: E501
        self._listeid = None
        self._id = None
        self._type = None
        self.discriminator = None
        if listeid is not None:
            self.listeid = listeid
        if id is not None:
            self.id = id
        if type is not None:
            self.type = type

    @property
    def listeid(self):
        """Gets the listeid of this RelasjonBase.  # noqa: E501

        Id for listeegenskap relasjonen ligger i.  # noqa: E501

        :return: The listeid of this RelasjonBase.  # noqa: E501
        :rtype: int
        """
        return self._listeid

    @listeid.setter
    def listeid(self, listeid):
        """Sets the listeid of this RelasjonBase.

        Id for listeegenskap relasjonen ligger i.  # noqa: E501

        :param listeid: The listeid of this RelasjonBase.  # noqa: E501
        :type: int
        """

        self._listeid = listeid

    @property
    def id(self):
        """Gets the id of this RelasjonBase.  # noqa: E501

        Id for egenskapen/relasjonen  # noqa: E501

        :return: The id of this RelasjonBase.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RelasjonBase.

        Id for egenskapen/relasjonen  # noqa: E501

        :param id: The id of this RelasjonBase.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def type(self):
        """Gets the type of this RelasjonBase.  # noqa: E501


        :return: The type of this RelasjonBase.  # noqa: E501
        :rtype: RelasjonbaseType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RelasjonBase.


        :param type: The type of this RelasjonBase.  # noqa: E501
        :type: RelasjonbaseType
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RelasjonBase, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RelasjonBase):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
