# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Riksvegrute(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'navn': 'str',
        'nummer': 'str',
        'periode': 'str',
        'beskrivelse': 'str',
        'fylker': 'list[int]',
        'kommuner': 'list[int]'
    }

    attribute_map = {
        'id': 'id',
        'navn': 'navn',
        'nummer': 'nummer',
        'periode': 'periode',
        'beskrivelse': 'beskrivelse',
        'fylker': 'fylker',
        'kommuner': 'kommuner'
    }

    def __init__(self, id=None, navn=None, nummer=None, periode=None, beskrivelse=None, fylker=None, kommuner=None):  # noqa: E501
        """Riksvegrute - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._navn = None
        self._nummer = None
        self._periode = None
        self._beskrivelse = None
        self._fylker = None
        self._kommuner = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if navn is not None:
            self.navn = navn
        if nummer is not None:
            self.nummer = nummer
        if periode is not None:
            self.periode = periode
        if beskrivelse is not None:
            self.beskrivelse = beskrivelse
        if fylker is not None:
            self.fylker = fylker
        if kommuner is not None:
            self.kommuner = kommuner

    @property
    def id(self):
        """Gets the id of this Riksvegrute.  # noqa: E501


        :return: The id of this Riksvegrute.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Riksvegrute.


        :param id: The id of this Riksvegrute.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def navn(self):
        """Gets the navn of this Riksvegrute.  # noqa: E501


        :return: The navn of this Riksvegrute.  # noqa: E501
        :rtype: str
        """
        return self._navn

    @navn.setter
    def navn(self, navn):
        """Sets the navn of this Riksvegrute.


        :param navn: The navn of this Riksvegrute.  # noqa: E501
        :type: str
        """

        self._navn = navn

    @property
    def nummer(self):
        """Gets the nummer of this Riksvegrute.  # noqa: E501


        :return: The nummer of this Riksvegrute.  # noqa: E501
        :rtype: str
        """
        return self._nummer

    @nummer.setter
    def nummer(self, nummer):
        """Sets the nummer of this Riksvegrute.


        :param nummer: The nummer of this Riksvegrute.  # noqa: E501
        :type: str
        """

        self._nummer = nummer

    @property
    def periode(self):
        """Gets the periode of this Riksvegrute.  # noqa: E501


        :return: The periode of this Riksvegrute.  # noqa: E501
        :rtype: str
        """
        return self._periode

    @periode.setter
    def periode(self, periode):
        """Sets the periode of this Riksvegrute.


        :param periode: The periode of this Riksvegrute.  # noqa: E501
        :type: str
        """

        self._periode = periode

    @property
    def beskrivelse(self):
        """Gets the beskrivelse of this Riksvegrute.  # noqa: E501


        :return: The beskrivelse of this Riksvegrute.  # noqa: E501
        :rtype: str
        """
        return self._beskrivelse

    @beskrivelse.setter
    def beskrivelse(self, beskrivelse):
        """Sets the beskrivelse of this Riksvegrute.


        :param beskrivelse: The beskrivelse of this Riksvegrute.  # noqa: E501
        :type: str
        """

        self._beskrivelse = beskrivelse

    @property
    def fylker(self):
        """Gets the fylker of this Riksvegrute.  # noqa: E501

        Fylker riksvegruten dekker  # noqa: E501

        :return: The fylker of this Riksvegrute.  # noqa: E501
        :rtype: list[int]
        """
        return self._fylker

    @fylker.setter
    def fylker(self, fylker):
        """Sets the fylker of this Riksvegrute.

        Fylker riksvegruten dekker  # noqa: E501

        :param fylker: The fylker of this Riksvegrute.  # noqa: E501
        :type: list[int]
        """

        self._fylker = fylker

    @property
    def kommuner(self):
        """Gets the kommuner of this Riksvegrute.  # noqa: E501

        Kommuner riksvegruten dekker  # noqa: E501

        :return: The kommuner of this Riksvegrute.  # noqa: E501
        :rtype: list[int]
        """
        return self._kommuner

    @kommuner.setter
    def kommuner(self, kommuner):
        """Sets the kommuner of this Riksvegrute.

        Kommuner riksvegruten dekker  # noqa: E501

        :param kommuner: The kommuner of this Riksvegrute.  # noqa: E501
        :type: list[int]
        """

        self._kommuner = kommuner

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Riksvegrute, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Riksvegrute):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
