# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Statistikk(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'antall': 'int',
        'lengde': 'float'
    }

    attribute_map = {
        'antall': 'antall',
        'lengde': 'lengde'
    }

    def __init__(self, antall=None, lengde=None):  # noqa: E501
        """Statistikk - a model defined in Swagger"""  # noqa: E501
        self._antall = None
        self._lengde = None
        self.discriminator = None
        if antall is not None:
            self.antall = antall
        if lengde is not None:
            self.lengde = lengde

    @property
    def antall(self):
        """Gets the antall of this Statistikk.  # noqa: E501

        Antallet objekter  # noqa: E501

        :return: The antall of this Statistikk.  # noqa: E501
        :rtype: int
        """
        return self._antall

    @antall.setter
    def antall(self, antall):
        """Sets the antall of this Statistikk.

        Antallet objekter  # noqa: E501

        :param antall: The antall of this Statistikk.  # noqa: E501
        :type: int
        """

        self._antall = antall

    @property
    def lengde(self):
        """Gets the lengde of this Statistikk.  # noqa: E501

        Den summerte lengden av objektene  # noqa: E501

        :return: The lengde of this Statistikk.  # noqa: E501
        :rtype: float
        """
        return self._lengde

    @lengde.setter
    def lengde(self, lengde):
        """Sets the lengde of this Statistikk.

        Den summerte lengden av objektene  # noqa: E501

        :param lengde: The lengde of this Statistikk.  # noqa: E501
        :type: float
        """

        self._lengde = lengde

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Statistikk, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Statistikk):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
