# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.vegobjekt_metadata import VegobjektMetadata  # noqa: F401,E501

class TransaksjonVegobjektMetadata(VegobjektMetadata):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'transaksjonstype': 'str'
    }
    if hasattr(VegobjektMetadata, "swagger_types"):
        swagger_types.update(VegobjektMetadata.swagger_types)

    attribute_map = {
        'transaksjonstype': 'transaksjonstype'
    }
    if hasattr(VegobjektMetadata, "attribute_map"):
        attribute_map.update(VegobjektMetadata.attribute_map)

    def __init__(self, transaksjonstype=None, *args, **kwargs):  # noqa: E501
        """TransaksjonVegobjektMetadata - a model defined in Swagger"""  # noqa: E501
        self._transaksjonstype = None
        self.discriminator = None
        if transaksjonstype is not None:
            self.transaksjonstype = transaksjonstype
        VegobjektMetadata.__init__(self, *args, **kwargs)

    @property
    def transaksjonstype(self):
        """Gets the transaksjonstype of this TransaksjonVegobjektMetadata.  # noqa: E501


        :return: The transaksjonstype of this TransaksjonVegobjektMetadata.  # noqa: E501
        :rtype: str
        """
        return self._transaksjonstype

    @transaksjonstype.setter
    def transaksjonstype(self, transaksjonstype):
        """Sets the transaksjonstype of this TransaksjonVegobjektMetadata.


        :param transaksjonstype: The transaksjonstype of this TransaksjonVegobjektMetadata.  # noqa: E501
        :type: str
        """
        allowed_values = ["CREATED", "MODIFIED", "DELETED"]  # noqa: E501
        if transaksjonstype not in allowed_values:
            raise ValueError(
                "Invalid value for `transaksjonstype` ({0}), must be one of {1}"  # noqa: E501
                .format(transaksjonstype, allowed_values)
            )

        self._transaksjonstype = transaksjonstype

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TransaksjonVegobjektMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransaksjonVegobjektMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
