# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.vegobjekt_type_egenskap_base import VegobjektTypeEgenskapBase  # noqa: F401,E501

class VegobjektTypeEgenskapListe(VegobjektTypeEgenskapBase):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'maksimalt_antall_verdier': 'int',
        'minimalt_antall_verdier': 'int',
        'innhold': 'VegobjekttypeEgenskap'
    }
    if hasattr(VegobjektTypeEgenskapBase, "swagger_types"):
        swagger_types.update(VegobjektTypeEgenskapBase.swagger_types)

    attribute_map = {
        'maksimalt_antall_verdier': 'maksimalt_antall_verdier',
        'minimalt_antall_verdier': 'minimalt_antall_verdier',
        'innhold': 'innhold'
    }
    if hasattr(VegobjektTypeEgenskapBase, "attribute_map"):
        attribute_map.update(VegobjektTypeEgenskapBase.attribute_map)

    def __init__(self, maksimalt_antall_verdier=None, minimalt_antall_verdier=None, innhold=None, *args, **kwargs):  # noqa: E501
        """VegobjektTypeEgenskapListe - a model defined in Swagger"""  # noqa: E501
        self._maksimalt_antall_verdier = None
        self._minimalt_antall_verdier = None
        self._innhold = None
        self.discriminator = None
        if maksimalt_antall_verdier is not None:
            self.maksimalt_antall_verdier = maksimalt_antall_verdier
        if minimalt_antall_verdier is not None:
            self.minimalt_antall_verdier = minimalt_antall_verdier
        if innhold is not None:
            self.innhold = innhold
        VegobjektTypeEgenskapBase.__init__(self, *args, **kwargs)

    @property
    def maksimalt_antall_verdier(self):
        """Gets the maksimalt_antall_verdier of this VegobjektTypeEgenskapListe.  # noqa: E501


        :return: The maksimalt_antall_verdier of this VegobjektTypeEgenskapListe.  # noqa: E501
        :rtype: int
        """
        return self._maksimalt_antall_verdier

    @maksimalt_antall_verdier.setter
    def maksimalt_antall_verdier(self, maksimalt_antall_verdier):
        """Sets the maksimalt_antall_verdier of this VegobjektTypeEgenskapListe.


        :param maksimalt_antall_verdier: The maksimalt_antall_verdier of this VegobjektTypeEgenskapListe.  # noqa: E501
        :type: int
        """

        self._maksimalt_antall_verdier = maksimalt_antall_verdier

    @property
    def minimalt_antall_verdier(self):
        """Gets the minimalt_antall_verdier of this VegobjektTypeEgenskapListe.  # noqa: E501


        :return: The minimalt_antall_verdier of this VegobjektTypeEgenskapListe.  # noqa: E501
        :rtype: int
        """
        return self._minimalt_antall_verdier

    @minimalt_antall_verdier.setter
    def minimalt_antall_verdier(self, minimalt_antall_verdier):
        """Sets the minimalt_antall_verdier of this VegobjektTypeEgenskapListe.


        :param minimalt_antall_verdier: The minimalt_antall_verdier of this VegobjektTypeEgenskapListe.  # noqa: E501
        :type: int
        """

        self._minimalt_antall_verdier = minimalt_antall_verdier

    @property
    def innhold(self):
        """Gets the innhold of this VegobjektTypeEgenskapListe.  # noqa: E501


        :return: The innhold of this VegobjektTypeEgenskapListe.  # noqa: E501
        :rtype: VegobjekttypeEgenskap
        """
        return self._innhold

    @innhold.setter
    def innhold(self, innhold):
        """Sets the innhold of this VegobjektTypeEgenskapListe.


        :param innhold: The innhold of this VegobjektTypeEgenskapListe.  # noqa: E501
        :type: VegobjekttypeEgenskap
        """

        self._innhold = innhold

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VegobjektTypeEgenskapListe, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VegobjektTypeEgenskapListe):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
