# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.vegobjekt_type_egenskap_primitiv import VegobjektTypeEgenskapPrimitiv  # noqa: F401,E501

class VegobjektTypeEgenskapTid(VegobjektTypeEgenskapPrimitiv):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'standardverdi': 'str',
        'min_anbefalt': 'str',
        'maks_anbefalt': 'str',
        'feltmnster': 'str'
    }
    if hasattr(VegobjektTypeEgenskapPrimitiv, "swagger_types"):
        swagger_types.update(VegobjektTypeEgenskapPrimitiv.swagger_types)

    attribute_map = {
        'standardverdi': 'standardverdi',
        'min_anbefalt': 'min_anbefalt',
        'maks_anbefalt': 'maks_anbefalt',
        'feltmnster': 'feltmønster'
    }
    if hasattr(VegobjektTypeEgenskapPrimitiv, "attribute_map"):
        attribute_map.update(VegobjektTypeEgenskapPrimitiv.attribute_map)

    def __init__(self, standardverdi=None, min_anbefalt=None, maks_anbefalt=None, feltmnster=None, *args, **kwargs):  # noqa: E501
        """VegobjektTypeEgenskapTid - a model defined in Swagger"""  # noqa: E501
        self._standardverdi = None
        self._min_anbefalt = None
        self._maks_anbefalt = None
        self._feltmnster = None
        self.discriminator = None
        if standardverdi is not None:
            self.standardverdi = standardverdi
        if min_anbefalt is not None:
            self.min_anbefalt = min_anbefalt
        if maks_anbefalt is not None:
            self.maks_anbefalt = maks_anbefalt
        if feltmnster is not None:
            self.feltmnster = feltmnster
        VegobjektTypeEgenskapPrimitiv.__init__(self, *args, **kwargs)

    @property
    def standardverdi(self):
        """Gets the standardverdi of this VegobjektTypeEgenskapTid.  # noqa: E501


        :return: The standardverdi of this VegobjektTypeEgenskapTid.  # noqa: E501
        :rtype: str
        """
        return self._standardverdi

    @standardverdi.setter
    def standardverdi(self, standardverdi):
        """Sets the standardverdi of this VegobjektTypeEgenskapTid.


        :param standardverdi: The standardverdi of this VegobjektTypeEgenskapTid.  # noqa: E501
        :type: str
        """

        self._standardverdi = standardverdi

    @property
    def min_anbefalt(self):
        """Gets the min_anbefalt of this VegobjektTypeEgenskapTid.  # noqa: E501


        :return: The min_anbefalt of this VegobjektTypeEgenskapTid.  # noqa: E501
        :rtype: str
        """
        return self._min_anbefalt

    @min_anbefalt.setter
    def min_anbefalt(self, min_anbefalt):
        """Sets the min_anbefalt of this VegobjektTypeEgenskapTid.


        :param min_anbefalt: The min_anbefalt of this VegobjektTypeEgenskapTid.  # noqa: E501
        :type: str
        """

        self._min_anbefalt = min_anbefalt

    @property
    def maks_anbefalt(self):
        """Gets the maks_anbefalt of this VegobjektTypeEgenskapTid.  # noqa: E501


        :return: The maks_anbefalt of this VegobjektTypeEgenskapTid.  # noqa: E501
        :rtype: str
        """
        return self._maks_anbefalt

    @maks_anbefalt.setter
    def maks_anbefalt(self, maks_anbefalt):
        """Sets the maks_anbefalt of this VegobjektTypeEgenskapTid.


        :param maks_anbefalt: The maks_anbefalt of this VegobjektTypeEgenskapTid.  # noqa: E501
        :type: str
        """

        self._maks_anbefalt = maks_anbefalt

    @property
    def feltmnster(self):
        """Gets the feltmnster of this VegobjektTypeEgenskapTid.  # noqa: E501


        :return: The feltmnster of this VegobjektTypeEgenskapTid.  # noqa: E501
        :rtype: str
        """
        return self._feltmnster

    @feltmnster.setter
    def feltmnster(self, feltmnster):
        """Sets the feltmnster of this VegobjektTypeEgenskapTid.


        :param feltmnster: The feltmnster of this VegobjektTypeEgenskapTid.  # noqa: E501
        :type: str
        """

        self._feltmnster = feltmnster

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VegobjektTypeEgenskapTid, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VegobjektTypeEgenskapTid):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
