# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VegobjektLokasjonStedfestingPunkt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'veglenkesekvensid': 'int',
        'relativ_posisjon': 'float',
        'kortform': 'str',
        'kjrefelt': 'Kjorefelt',
        'sideposisjon': 'Sideposisjon',
        'retning': 'Retning'
    }

    attribute_map = {
        'type': 'type',
        'veglenkesekvensid': 'veglenkesekvensid',
        'relativ_posisjon': 'relativPosisjon',
        'kortform': 'kortform',
        'kjrefelt': 'kjørefelt',
        'sideposisjon': 'sideposisjon',
        'retning': 'retning'
    }

    def __init__(self, type=None, veglenkesekvensid=None, relativ_posisjon=None, kortform=None, kjrefelt=None, sideposisjon=None, retning=None):  # noqa: E501
        """VegobjektLokasjonStedfestingPunkt - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._veglenkesekvensid = None
        self._relativ_posisjon = None
        self._kortform = None
        self._kjrefelt = None
        self._sideposisjon = None
        self._retning = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if veglenkesekvensid is not None:
            self.veglenkesekvensid = veglenkesekvensid
        if relativ_posisjon is not None:
            self.relativ_posisjon = relativ_posisjon
        if kortform is not None:
            self.kortform = kortform
        if kjrefelt is not None:
            self.kjrefelt = kjrefelt
        if sideposisjon is not None:
            self.sideposisjon = sideposisjon
        if retning is not None:
            self.retning = retning

    @property
    def type(self):
        """Gets the type of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501


        :return: The type of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this VegobjektLokasjonStedfestingPunkt.


        :param type: The type of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def veglenkesekvensid(self):
        """Gets the veglenkesekvensid of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501


        :return: The veglenkesekvensid of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501
        :rtype: int
        """
        return self._veglenkesekvensid

    @veglenkesekvensid.setter
    def veglenkesekvensid(self, veglenkesekvensid):
        """Sets the veglenkesekvensid of this VegobjektLokasjonStedfestingPunkt.


        :param veglenkesekvensid: The veglenkesekvensid of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501
        :type: int
        """

        self._veglenkesekvensid = veglenkesekvensid

    @property
    def relativ_posisjon(self):
        """Gets the relativ_posisjon of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501


        :return: The relativ_posisjon of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501
        :rtype: float
        """
        return self._relativ_posisjon

    @relativ_posisjon.setter
    def relativ_posisjon(self, relativ_posisjon):
        """Sets the relativ_posisjon of this VegobjektLokasjonStedfestingPunkt.


        :param relativ_posisjon: The relativ_posisjon of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501
        :type: float
        """

        self._relativ_posisjon = relativ_posisjon

    @property
    def kortform(self):
        """Gets the kortform of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501


        :return: The kortform of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501
        :rtype: str
        """
        return self._kortform

    @kortform.setter
    def kortform(self, kortform):
        """Sets the kortform of this VegobjektLokasjonStedfestingPunkt.


        :param kortform: The kortform of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501
        :type: str
        """

        self._kortform = kortform

    @property
    def kjrefelt(self):
        """Gets the kjrefelt of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501


        :return: The kjrefelt of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501
        :rtype: Kjorefelt
        """
        return self._kjrefelt

    @kjrefelt.setter
    def kjrefelt(self, kjrefelt):
        """Sets the kjrefelt of this VegobjektLokasjonStedfestingPunkt.


        :param kjrefelt: The kjrefelt of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501
        :type: Kjorefelt
        """

        self._kjrefelt = kjrefelt

    @property
    def sideposisjon(self):
        """Gets the sideposisjon of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501


        :return: The sideposisjon of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501
        :rtype: Sideposisjon
        """
        return self._sideposisjon

    @sideposisjon.setter
    def sideposisjon(self, sideposisjon):
        """Sets the sideposisjon of this VegobjektLokasjonStedfestingPunkt.


        :param sideposisjon: The sideposisjon of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501
        :type: Sideposisjon
        """

        self._sideposisjon = sideposisjon

    @property
    def retning(self):
        """Gets the retning of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501


        :return: The retning of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501
        :rtype: Retning
        """
        return self._retning

    @retning.setter
    def retning(self, retning):
        """Sets the retning of this VegobjektLokasjonStedfestingPunkt.


        :param retning: The retning of this VegobjektLokasjonStedfestingPunkt.  # noqa: E501
        :type: Retning
        """

        self._retning = retning

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VegobjektLokasjonStedfestingPunkt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VegobjektLokasjonStedfestingPunkt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
