# coding: utf-8

"""
    NVDB API LES V3

    API for å lese vegobjekter, vegnett og transaksjoner fra NVDB  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: nvdb@vegvesen.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class PosisjonApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def posisjon_get(self, x_client, **kwargs):  # noqa: E501
        """posisjon_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.posisjon_get(x_client, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_client: Noe som identifiserer klienten eller fagsystemet. Eksempler: «Vegkart», «NVDB Skrive-API». Må settes dersom User-Agent ikke er satt. X-Client foretrekkes. (required)
        :param str x_client_session: Settes for å identifisere en samling med requester, for eksempel en brukersesjon. (bruk i såfall en uuid eller noe lignende, ikke brukernavn eller epost)
        :param float nord: Nordlig koordinat
        :param float ost: Østlig koordinat
        :param float lat: Breddegrad
        :param float lon: Lengdegrad
        :param int maks_avstand: Angir søkeavstand i meter
        :param int maks_antall: Angir hvor mange resultater som maksimum skal returneres
        :param bool konnekteringslenker: Angir om det skal returneres treff på konnekteringslenker
        :param bool detaljerte_lenker: Angir om det skal returneres treff på detaljerte vegnettsnivå
        :param list[str] vegsystemreferanse: Filtrer vegobjekter på [vegsystemreferanse](https://api.vegdata.no/v3/vegsystemreferanse.html) Kommaseparert liste.
        :param str srid: Angir hvilket geografisk referansesystem geometrien skal returneres i.   Mer informasjon: [EPSG:6173](https://epsg.io/6173) [EPSG:6173 i NVDB](https://github.com/nvdb-vegdata/utviklerkonferanse-2018/blob/master/doc/epsg6173.md) [EPSG:4326](http://epsg.io/4326)
        :return: list[Posisjonsresultat]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.posisjon_get_with_http_info(x_client, **kwargs)  # noqa: E501
        else:
            (data) = self.posisjon_get_with_http_info(x_client, **kwargs)  # noqa: E501
            return data

    def posisjon_get_with_http_info(self, x_client, **kwargs):  # noqa: E501
        """posisjon_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.posisjon_get_with_http_info(x_client, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_client: Noe som identifiserer klienten eller fagsystemet. Eksempler: «Vegkart», «NVDB Skrive-API». Må settes dersom User-Agent ikke er satt. X-Client foretrekkes. (required)
        :param str x_client_session: Settes for å identifisere en samling med requester, for eksempel en brukersesjon. (bruk i såfall en uuid eller noe lignende, ikke brukernavn eller epost)
        :param float nord: Nordlig koordinat
        :param float ost: Østlig koordinat
        :param float lat: Breddegrad
        :param float lon: Lengdegrad
        :param int maks_avstand: Angir søkeavstand i meter
        :param int maks_antall: Angir hvor mange resultater som maksimum skal returneres
        :param bool konnekteringslenker: Angir om det skal returneres treff på konnekteringslenker
        :param bool detaljerte_lenker: Angir om det skal returneres treff på detaljerte vegnettsnivå
        :param list[str] vegsystemreferanse: Filtrer vegobjekter på [vegsystemreferanse](https://api.vegdata.no/v3/vegsystemreferanse.html) Kommaseparert liste.
        :param str srid: Angir hvilket geografisk referansesystem geometrien skal returneres i.   Mer informasjon: [EPSG:6173](https://epsg.io/6173) [EPSG:6173 i NVDB](https://github.com/nvdb-vegdata/utviklerkonferanse-2018/blob/master/doc/epsg6173.md) [EPSG:4326](http://epsg.io/4326)
        :return: list[Posisjonsresultat]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_client', 'x_client_session', 'nord', 'ost', 'lat', 'lon', 'maks_avstand', 'maks_antall', 'konnekteringslenker', 'detaljerte_lenker', 'vegsystemreferanse', 'srid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method posisjon_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_client' is set
        if ('x_client' not in params or
                params['x_client'] is None):
            raise ValueError("Missing the required parameter `x_client` when calling `posisjon_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'nord' in params:
            query_params.append(('nord', params['nord']))  # noqa: E501
        if 'ost' in params:
            query_params.append(('ost', params['ost']))  # noqa: E501
        if 'lat' in params:
            query_params.append(('lat', params['lat']))  # noqa: E501
        if 'lon' in params:
            query_params.append(('lon', params['lon']))  # noqa: E501
        if 'maks_avstand' in params:
            query_params.append(('maks_avstand', params['maks_avstand']))  # noqa: E501
        if 'maks_antall' in params:
            query_params.append(('maks_antall', params['maks_antall']))  # noqa: E501
        if 'konnekteringslenker' in params:
            query_params.append(('konnekteringslenker', params['konnekteringslenker']))  # noqa: E501
        if 'detaljerte_lenker' in params:
            query_params.append(('detaljerte_lenker', params['detaljerte_lenker']))  # noqa: E501
        if 'vegsystemreferanse' in params:
            query_params.append(('Vegsystemreferanse', params['vegsystemreferanse']))  # noqa: E501
            collection_formats['Vegsystemreferanse'] = 'space'  # noqa: E501
        if 'srid' in params:
            query_params.append(('srid', params['srid']))  # noqa: E501

        header_params = {}
        if 'x_client' in params:
            header_params['X-Client'] = params['x_client']  # noqa: E501
        if 'x_client_session' in params:
            header_params['X-Client-Session'] = params['x_client_session']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.vegvesen.nvdb-v3-rev1+json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/posisjon', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Posisjonsresultat]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def veg_batch_get(self, **kwargs):  # noqa: E501
        """veg_batch_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.veg_batch_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str vegsystemreferanser:
        :param str veglenkesekvenser:
        :param list[int] kommune: Filtrer på kommune. Kommaseparert liste. Se /omrader/kommuner for mulige verdier.
        :param str srid: Angir hvilket geografisk referansesystem geometrien skal returneres i.   Mer informasjon: [EPSG:6173](https://epsg.io/6173) [EPSG:6173 i NVDB](https://github.com/nvdb-vegdata/utviklerkonferanse-2018/blob/master/doc/epsg6173.md) [EPSG:4326](http://epsg.io/4326)
        :return: dict(str, Posisjonsresultat)
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.veg_batch_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.veg_batch_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def veg_batch_get_with_http_info(self, **kwargs):  # noqa: E501
        """veg_batch_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.veg_batch_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str vegsystemreferanser:
        :param str veglenkesekvenser:
        :param list[int] kommune: Filtrer på kommune. Kommaseparert liste. Se /omrader/kommuner for mulige verdier.
        :param str srid: Angir hvilket geografisk referansesystem geometrien skal returneres i.   Mer informasjon: [EPSG:6173](https://epsg.io/6173) [EPSG:6173 i NVDB](https://github.com/nvdb-vegdata/utviklerkonferanse-2018/blob/master/doc/epsg6173.md) [EPSG:4326](http://epsg.io/4326)
        :return: dict(str, Posisjonsresultat)
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['vegsystemreferanser', 'veglenkesekvenser', 'kommune', 'srid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method veg_batch_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'vegsystemreferanser' in params:
            query_params.append(('vegsystemreferanser', params['vegsystemreferanser']))  # noqa: E501
        if 'veglenkesekvenser' in params:
            query_params.append(('veglenkesekvenser', params['veglenkesekvenser']))  # noqa: E501
        if 'kommune' in params:
            query_params.append(('Kommune', params['kommune']))  # noqa: E501
            collection_formats['Kommune'] = 'space'  # noqa: E501
        if 'srid' in params:
            query_params.append(('srid', params['srid']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.vegvesen.nvdb-v3-rev1+json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/veg/batch', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='dict(str, Posisjonsresultat)',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def veg_get(self, **kwargs):  # noqa: E501
        """veg_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.veg_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str vegsystemreferanse: Filtrer vegobjekter på [vegsystemreferanse](https://api.vegdata.no/v3/vegsystemreferanse.html)
        :param str veglenkesekvens: Filtrer vegobjekter på stedfesting på vegnettet. Format: `posisjon@veglenkesekvensid`
        :param str srid: Angir hvilket geografisk referansesystem geometrien skal returneres i.   Mer informasjon: [EPSG:6173](https://epsg.io/6173) [EPSG:6173 i NVDB](https://github.com/nvdb-vegdata/utviklerkonferanse-2018/blob/master/doc/epsg6173.md) [EPSG:4326](http://epsg.io/4326)
        :param list[int] kommune: Filtrer på kommune. Kommaseparert liste. Se /omrader/kommuner for mulige verdier.
        :return: Posisjonsresultat
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.veg_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.veg_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def veg_get_with_http_info(self, **kwargs):  # noqa: E501
        """veg_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.veg_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str vegsystemreferanse: Filtrer vegobjekter på [vegsystemreferanse](https://api.vegdata.no/v3/vegsystemreferanse.html)
        :param str veglenkesekvens: Filtrer vegobjekter på stedfesting på vegnettet. Format: `posisjon@veglenkesekvensid`
        :param str srid: Angir hvilket geografisk referansesystem geometrien skal returneres i.   Mer informasjon: [EPSG:6173](https://epsg.io/6173) [EPSG:6173 i NVDB](https://github.com/nvdb-vegdata/utviklerkonferanse-2018/blob/master/doc/epsg6173.md) [EPSG:4326](http://epsg.io/4326)
        :param list[int] kommune: Filtrer på kommune. Kommaseparert liste. Se /omrader/kommuner for mulige verdier.
        :return: Posisjonsresultat
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['vegsystemreferanse', 'veglenkesekvens', 'srid', 'kommune']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method veg_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'vegsystemreferanse' in params:
            query_params.append(('vegsystemreferanse', params['vegsystemreferanse']))  # noqa: E501
        if 'veglenkesekvens' in params:
            query_params.append(('veglenkesekvens', params['veglenkesekvens']))  # noqa: E501
        if 'srid' in params:
            query_params.append(('srid', params['srid']))  # noqa: E501
        if 'kommune' in params:
            query_params.append(('Kommune', params['kommune']))  # noqa: E501
            collection_formats['Kommune'] = 'space'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.vegvesen.nvdb-v3-rev1+json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/veg', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Posisjonsresultat',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
